apiVersion: v1
kind: Service
metadata:
  name: product-db
  namespace: fiap
  labels:
    app: product-db
spec:
  selector:
    app: product-db
  ports:
    - port: 27017
      targetPort: 27017
      name: product-db
  type: ClusterIP