apiVersion: v1
kind: Service
metadata:
  name: product-service
  labels:
    app: product-service
spec:
  selector:
    app: product-service
  ports:
    - port: 3002
      targetPort: 3002
      name: rest
  type: ClusterIP